# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10

  pre_build:
    commands:
      - aws --version
      - node --version
      - docker --version
      - echo node port
      - NODE_PORT=$NODE_PORT
      - echo image uri ${IMAGE_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Image tag ${IMAGE_TAG}
      - APP_NAME=${APP_NAME}
      - echo Building for application ${APP_NAME}
      - Environment=${Environment}
      - echo Application Environment ${Environment}
      - echo node image uri ${NODE_URI}
      - CONTAINER_NAME=${APP_NAME}-${Environment}-container-def
      - echo Using container path ${CONTAINER_NAME}
      - echo "Create output directory for artifacts"
      - mkdir -p output
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - echo Installing Mocha...
      - npm install -g mocha
      #- npm run test
  build:
    commands:
      - echo Build started on `date`
      - echo "Current working directory"
      - pwd
      - echo "Packaging lambdas .. "
      - make -B lambda
      - echo "after lambda"
      - pwd
      - echo Building images...
      - docker build . -t ${IMAGE_URI}:latest --build-arg NODE_IMAGE=${NODE_URI}:latest
      - echo Tag the docker image
      - docker tag ${IMAGE_URI}:latest ${IMAGE_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Push image to ECR
      - docker push ${IMAGE_URI}:${IMAGE_TAG}
      - docker push ${IMAGE_URI}:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' ${CONTAINER_NAME} ${IMAGE_URI}:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - mv imagedefinitions.json output/

# Include only the files required for your application to run.
artifacts:
  base-directory: output
  discard-paths: yes
  type: zip
  files:
    - '**/*'