AWSTemplateFormatVersion: "2010-09-09"

Description: This repo create required ECS resources

Parameters:
  AppName:
    Type: String
    Description: "Name of the application"

  Environment:
    Type: String
    Description: "application environment"
    Default: development

Resources:
  Ecr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}_${Environment}
    