AWSTemplateFormatVersion: '2010-09-09'

Description: Resources shared across service stacks

Metadata:
  Version:
    Description: v1.0.0

Parameters:
  Environment:
    Type: String
    Description: "application environment"
    Default: development
  AppName:
    Type: String
    Description: "Name of the application"
    Default: test

Conditions:
  isProduction: !Equals [!Ref Environment, 'production']

Resources:
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${AppName}-${Environment}-lambda"

  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: HelloWorld
      FunctionName: !Sub ${AppName}-${Environment}-helloworld
      Runtime: nodejs14.x
      Role: !ImportValue LambdaExecutionRole
      Timeout: 500
      Environment:
        Variables:
            NODE_ENV: !Sub ${Environment}
      Code: ./src/helloworld/.
      Handler: hello.HelloWorldHandler

  UpdateDynamoDBFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Sync hospital list
      FunctionName: !Sub ${AppName}-${Environment}-updateDynamoDB
      Runtime: nodejs14.x
      Role: !ImportValue LambdaExecutionRole
      Timeout: 500
      Environment:
        Variables:
            NODE_ENV: !Sub ${Environment}
      Code: ./src/updateDynamoDB/.
      Handler: index.handler


